### ISSUE TITLE
Comparing with PostgREST

### ISSUE THREAD

**Issue by ppKrauss** [GIScience/measures-rest#3]
Hi, 
&nbsp; (sorry if it's a wrong place to post a question and maybe a suggestion)

We use FOSS software and all measurements are stored in a  PostgreSQL+PostGIS database. 

We have tested applications using good 64 bits [geocode systems](https://en.wikipedia.org/wiki/Geocode#Geocode_system) like [S2 geometry](https://s2geometry.io/) and [fast binary Geohash](https://mmcloughlin.com/posts/geohash-assembly)... 

Measures-REST seems like a good alternative because is "all in one" project oriented to DGGS (equal-area grid).  But as back-end, seems that [PostgREST](http://postgrest.org/en/v6.0/) is as fast as  Measures-REST... Is there any Measures-REST  performance study? Or, ideal, a way to split it into parts, to use only the DGGS  part in a PostgreSQL extension.

**Comment by franz-benjamin** [comment]
... wrong place.  `Measure REST` just makes use of DGGSs.
